fos_rest:
  view:
    view_response_listener:  true
  param_fetcher_listener: true
  body_listener: true
  format_listener:
    enabled: true
    rules:
      - { path: ^/, prefer_extension: false, fallback_format: json, priorities: [ json ] }
  exception:
    codes:
      Doctrine\ORM\EntityNotFoundException: 404