# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Note! You can configure the same rates source with other id, when the their API is the same as in ECB website.
    App\RatesSources\Providers\Ecb\EcbRatesSource:
        class: App\RatesSources\Providers\Ecb\EcbRatesSource
        arguments:
            - 'www.ecb.europa.eu'
            - 'https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml'
            - 'EUR'

    # Optionally, when the Bank of England buy ECB software and will expose the same api for GBP
    # We can configure the new source like that (if the API has not changed):
#    App\RatesSources\Providers\UK\BankOfEnglandRatesSource:
#        class: App\RatesSources\Providers\Ecb\EcbRatesSource
#        arguments:
#            - 'www.bankofengland.co.uk/'
#            - 'https://www.bankofengland.co.uk//stats/eurofxref/eurofxref-daily.xml'
#            - 'GBP'

    App\RatesSources\Providers\Coindesk\CoindeskRatesSource:
        class: App\RatesSources\Providers\Coindesk\CoindeskRatesSource
        arguments:
            - 'api.coindesk.com'
            - 'https://api.coindesk.com/v1/bpi/historical/close.json'

    App\Service\RatesPullingService:
        class: App\Service\RatesPullingService
        arguments:
            - '@App\Repository\CurrencyRepository'
            - '@App\Repository\RateRepository'
            - '@App\Repository\SourceRepository'
            - '@App\RatesSources\Providers\Ecb\EcbRatesSource'
            - '@App\RatesSources\Providers\Coindesk\CoindeskRatesSource'